Repository DeveloperAcademy-POSTECH/MC3-Team11-BeyondThe3F, pull requests merged in 2023-08, with the labels that each got.

#158 [Feat] MapView 음악 기능 추가
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/MC3_BeyondThe3FApp.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/AppIcon.appiconset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/AppIcon.appiconset/Icon.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/ShazamView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
Labels: Feat, Fix

#167 [Fix] MusicPlay 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Fix

#169 [Feat] #166 - ToastComponentView 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ToastComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
Labels: Feat

#174 [Fix] 전체 플로우 에러 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
Labels: Fix

#179 [Fix] #175 - 디자인 디테일 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ToastComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
Labels: Fix

#182 Hotfix/#181
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/ShazamView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
Labels: Fix

#184 [Fix] #183 - playlist delete index 에러 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/xcshareddata/xcschemes/MC3-BeyondThe3F.xcscheme
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/DateExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/Double.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/dummy.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Fix

#187 [Refactor] Map에 대한 데이터, 로직을 MapViewModel로 분리
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Components/MidButtonComponent.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Components/SearchFailureComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Utils/Enum/NextProcess.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/BucketView/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/BucketView/CarouselView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/EditMapUIView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/MapView/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/MapView/MapUIKitView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/MapView/MapView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/ViewModel/MapSearchViewModel.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/ViewModel/MapViewModel.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/ViewModel/ShazamViewModel.swift
Labels: Refactor

#189 [Fix] Player 에러 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/EditView/EditMapUIView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/PlayView/MusicPlayView.swift
Labels: Fix

#192 [Feat] SubscriptionOffer 기능 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/Utils/Manager/MusicSubscriptionManager.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Source/View/PlayView/MusicPlayView.swift
Labels: Feat

#194 [setting] # 193 - app store 심사 위해 info.plist 파일 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
Labels: Setting
