Repository DeveloperAcademy-POSTECH/MC3-Team11-BeyondThe3F, pull requests merged in 2023-07, with the labels that each got.

#2 [Setting] #1 - README.md 제목 수정
  README.md
Labels: Setting

#7 [Feat] #6 - README.md 내용 추가
  README.md
Labels: Setting

#9 [setting] #4 - Muho Readme 추가
  Muho/README.md
Labels: Setting

#10 [Setting] #5 - henry 실습
  henry/README.md
Labels: Setting

#12 [Setting] Add README.md file on Austin Dir
  Austin/README.md
Labels: Setting

#14 [Setting] 디렉토리 정리 및 BaseTest 프로젝트 생성
  Austin/README.md
  BaseTest/BaseTest.xcodeproj/project.pbxproj
  BaseTest/BaseTest.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  BaseTest/BaseTest.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  BaseTest/BaseTest/Aewol/AewolView.swift
  BaseTest/BaseTest/Assets.xcassets/AccentColor.colorset/Contents.json
  BaseTest/BaseTest/Assets.xcassets/AppIcon.appiconset/Contents.json
  BaseTest/BaseTest/Assets.xcassets/Contents.json
  BaseTest/BaseTest/Austin/AustinView.swift
  BaseTest/BaseTest/BaseTestApp.swift
  BaseTest/BaseTest/ContentView.swift
  BaseTest/BaseTest/Henry/HenryView.swift
  BaseTest/BaseTest/Muho/MuhoView.swift
  BaseTest/BaseTest/Peter/PeterView.swift
  BaseTest/BaseTest/Preview Content/Preview Assets.xcassets/Contents.json
  BaseTest/README.md
  Muho/README.md
  henry/README.md
  jaesik/README.md
  jaesik/jaesik/README.md
Labels: Setting

#16 [Feat] BaseTest - 지도생성 및 음악 재생구현
  BaseTest/BaseTest.xcodeproj/project.pbxproj
  BaseTest/BaseTest/Assets.xcassets/annotaion0.imageset/Contents.json
  BaseTest/BaseTest/Assets.xcassets/annotaion0.imageset/Rectangle 3663.jpg
  BaseTest/BaseTest/Assets.xcassets/annotaion1.imageset/Contents.json
  BaseTest/BaseTest/Assets.xcassets/annotaion1.imageset/image 45.jpg
  BaseTest/BaseTest/Assets.xcassets/annotaion2.imageset/Contents.json
  BaseTest/BaseTest/Assets.xcassets/annotaion2.imageset/image 46.jpg
  BaseTest/BaseTest/Assets.xcassets/annotaion3.imageset/Contents.json
  BaseTest/BaseTest/Assets.xcassets/annotaion3.imageset/image 47.jpg
  BaseTest/BaseTest/Assets.xcassets/annotaionImage.imageset/Contents.json
  BaseTest/BaseTest/Assets.xcassets/annotaionImage.imageset/Group 27 (3).png
  BaseTest/BaseTest/Austin/AustinView.swift
  BaseTest/BaseTest/Austin/View/AustinHomeView.swift
  BaseTest/BaseTest/Austin/View/AustinMapSearchMusicListModalView.swift
  BaseTest/BaseTest/Austin/View/AustinMapView.swift
  BaseTest/BaseTest/Austin/View/AustinSearchView.swift
  BaseTest/BaseTest/Austin/View/Model/Annotation.swift
  BaseTest/BaseTest/Austin/View/Model/MusicItem.swift
  BaseTest/BaseTest/ContentView.swift
Labels: Feat

#20 [Setting] 프로젝트 기초 세팅
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Info.plist
  MC3-BeyondThe3F/MC3-BeyondThe3F/MC3_BeyondThe3FApp.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Preview Content/Preview Assets.xcassets/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Assets.xcassets/AccentColor.colorset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Assets.xcassets/AppIcon.appiconset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Assets.xcassets/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Store/MC3_BeyondThe3F.xcdatamodeld/.xccurrentversion
  MC3-BeyondThe3F/MC3-BeyondThe3F/Store/MC3_BeyondThe3F.xcdatamodeld/MC3_BeyondThe3F.xcdatamodel/contents
  MC3-BeyondThe3F/MC3-BeyondThe3F/Store/Persistence.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/DefaultCoreDataView.swift
Labels: Setting

#22 [Feat] 기초 TabView 및 TypoModifier 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ColorExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ViewExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Modifier/TypoModifier.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/AccentColor.colorset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/AppIcon.appiconset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Feat

#24 [Fix] #23 - Color, Typo 수정안 반영
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ColorExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ViewExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Modifier/TypoModifier.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Component/TextComponentView.swift
Labels: Fix

#28 [HotFix] #27 - .title() 모디파이어 제거
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
Labels: Fix

#32 [Design] Component 디자인 1차 - 누락된 Component 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/pinLocation.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/pinLocation.imageset/pinLocation.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Component/TextComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/AlbumCoverButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ButtonPlayComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/CameraButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/CameraComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/CancelComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ChevronBackwardComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ChevronForwardComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ContentsLargeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/EllipsisComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ForwardComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/GalleryButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/GearShapeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/IcloudAndArrowDownComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ListComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MagnifyingGlassComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MapComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MicComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchView2.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PauseComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PhotoComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PinLocationComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlayButtonBar.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlayButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlayLargeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlusComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/RandomPlayButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SaveAtThisLocationButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SaveButtonComponentView1.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SaveButtonComponentView2.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SavedBarComponentView1.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SavedBarComponentView2.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SavedBarComponentView3.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ScopeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ShuffleComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/TestComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/TrayComponentView.swift
Labels: Design

#34 Feature/#26 - 지도뷰 - Clustering 디자인
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicAnnotation.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItem.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion0.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion0.imageset/Rectangle 3663.jpg
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion1.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion1.imageset/image 45.jpg
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion2.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion2.imageset/image 46.jpg
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion3.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotaion3.imageset/image 47.jpg
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotationTest.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/annotationTest.imageset/image 61.jpg
  MC3-BeyondThe3F/MC3-BeyondThe3F/Store/MC3_BeyondThe3F.xcdatamodeld/MC3_BeyondThe3F.xcdatamodel/contents
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Feat, Design

#36 [feature]UI 컴포넌트 2차 제작
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/tape.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/tape.imageset/tape.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ContentsLargeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ContentsSmallComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ScopeButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/TapeComponentView.swift
Labels: Design

#37 [Design] 기존 Component 재사용성 높이기
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/AlbumCoverButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ButtonPlayComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/CameraButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/CameraComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/CancelComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ChevronBackwardComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ChevronForwardComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/EllipsisComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ForwardComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/GalleryButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/GearShapeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/IcloudAndArrowDownComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ListComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MagnifyingGlassComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MapComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MicComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MidButtonComponent.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchView2.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PauseComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PhotoComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlayButtonBar.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlayButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlayLargeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PlusComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PrimaryButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/RandomPlayButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SFImageComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SaveAtThisLocationButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SaveButtonComponentView1.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SaveButtonComponentView2.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SavedBarComponentView1.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SavedBarComponentView2.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SavedBarComponentView3.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ScopeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ShuffleComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SmallButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/TestComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/TrayComponentView.swift
Labels: Design

#38 [Fix] #26 - MapView UI 작업 및 Component 복구
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ContentsLargeComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Feat, Fix

#40 Feature/#26 - MapView playUI와 위치 보여주기
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ScopeButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Feat

#42 코어데이터세팅
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicAnnotation.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicDataModel.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemVO.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Store/MC3_BeyondThe3F.xcdatamodeld/MC3_BeyondThe3F.xcdatamodel/contents
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Feat

#43 Feature/#41 - MapView 개발 2차
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ColorExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/LocationHelper.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/ClusteringAnnotationView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/MusicAnnotationView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MapSearchComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MidButtonComponent.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Feat

#50 Feature/#44 - 지도 수정 뷰 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/LocationHelper.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/LocationManager.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
Labels: Feat, Fix

#52 [Hotfix] #51 - LocationHelper 제거
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Fix

#53 [Chore] #49 - MusicSeaechView 컴포넌트 파일 이름 변경
  BaseTest/BaseTest/Aewol/View/AlbumCell.swift
  BaseTest/BaseTest/Aewol/View/MusicAuthCell.swift
  BaseTest/BaseTest/Aewol/View/MusicCell.swift
  BaseTest/BaseTest/Aewol/View/MusicItemCell.swift
  BaseTest/BaseTest/Aewol/View/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
Labels: Setting

#56 [Fix] #55 - MusicSearchView 프리뷰 부분 코드 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
Labels: Fix

#57 Create .gitattributes
  .gitattributes
Labels: Setting

#60 [Setting] MusicKit, CoreLocation, ShazamKit 사용을 위한 info.plist 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
Labels: Setting

#68 [Feat] #33 - MusicSearchView 음악 검색 뷰 및 기능 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
Labels: Feat

#83 [Feat] #69 - MusicPlayView 음악 재생 뷰 및 기능 구현 (1차)
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/musicPlayImage.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/musicPlayImage.imageset/musicPlayImage.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#89 [Add] #88 - SFImageComponentView 파일에 backward 아이콘 추가
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SFImageComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#78 Feature/#47
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/PrimaryButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ScopeButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
Labels: Design

#58 [Fix] MapView 반응형 구현 및 EditMapPositionView 중앙 위치 값으려 변경
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Fix

#77 [Feat] ShazamView 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/ShazamManager.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ButtonPlayComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/ShazamView.swift
Labels: Feat, Design

#94 [Design] SearchComponentView 디자인 수정안 반영
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
Labels: Fix, Design

#87 [Feat] 보관함 뷰 구현 1차
  BaseTest/BaseTest/Henry/CitylistView.swift
  BaseTest/BaseTest/Henry/SearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
Labels: Feat, Design

#92 [Feat] MusicSearchView 기능 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/DateExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SFImageComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicSearchViewModel.swift
Labels: Feat, Fix

#98 [Feat] #90 - 데이터 모델 연결 (재생/일시정지, 앞 으로 스킵, 뒤로 스킵 기능)
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#100 [Feat] SearchView 연결
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
Labels: Feat

#105 [Fix] #104 - Muisclist List 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
Labels: Fix

#112 [Feat] #103 - 현재 재생 목록이 없을 때, 재생 중인 노래가 없을 때 뷰
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/musicPlayImageEmpty.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/TestImage.xcassets/musicPlayImageEmpty.imageset/musicPlayImageEmpty.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#114 [Fix] EditMapPositionView 현재 위치 기능, 지도 검색 기능 추가
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ScopeButtonComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
Labels: Feat

#118 [Fix] ShazamView 다시듣기 시 애니메이션 재생 문제 해결
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/ShazamView.swift
Labels: Fix

#121 [Feat] MapView 기능 추가 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/dummy.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/ClusteringAnnotationView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/MusicAnnotationView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
Labels: Feat

#124 [Feat] #113 - MusicPlayerComponentView 디테일 수정
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
Labels: Feat

#125 [Feat] 워크쓰루 플로우 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/NavigationHelper.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/welcomeSheetImage.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/welcomeSheetImage.imageset/welcomeSheetImage.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/WelcomeSheetComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTEditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTEditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTEditMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMapSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
Labels: Feat

#132 [Feat] #128 - MusicPlayView 디테일 작업 (2차)
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#134 [Feat] MusicItem 추가 제거 시 데이터 저장 담당 Singleton ViewModel 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
Labels: Feat

#136 [Feat] #127 - MusicPlayerComponentView
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicPlayer.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
Labels: Feat

#139 [Feat]/#131 - 온보딩 화면(워크 스루 디자인) 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/launchScreenImage1.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/launchScreenImage1.imageset/Group 2786.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/launchScreenImage2.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/launchScreenImage2.imageset/TuneSpot.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MapSearchComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTEditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTEditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTEditMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMapSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
Labels: Feat, Design

#141 [Feat] 음악 Create, Update 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Helper/NavigationHelper.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicItemDataModel.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/pinLocation.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/BucketView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicSearchComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/ViewModel/MusicItemUpdateViewModel.swift
Labels: Feat

#140 [Feat] #138 - MusicPlayView와 MusicPlayerComponentView 디테일 작업
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#144 [Feat] #143 - MusicPlayView와 MusicPlayerComponentView 디테일 작업 (3차)
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#129 [Feat] #104 - 보관함뷰 재생 기능 추가
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
Labels: Feat

#148 [Fix] #146 - MusicPlayView와 MusicPlayerComponentView 디테일 수정 (1차)
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicPlayerComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicPlayView.swift
Labels: Feat

#155 Feature/#131 샤잠 뷰 및 서치 실패 컴포넌트 구현
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/project.pbxproj
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/canNotFoundLogo.imageset/Contents.json
  MC3-BeyondThe3F/MC3-BeyondThe3F/Resource/Image.xcassets/canNotFoundLogo.imageset/canNotFoundMusicLogo.png
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/ButtonPlayComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SFImageComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/SearchFailureComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/ShazamView.swift
Labels: Design

#156 [Fix] 전체 플로우 에러 핸들링
  MC3-BeyondThe3F/MC3-BeyondThe3F.xcodeproj/xcshareddata/xcschemes/MC3-BeyondThe3F.xcscheme
  MC3-BeyondThe3F/MC3-BeyondThe3F/ContentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Global/Extension/ViewExtension.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/Model/MusicAnnotation.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/AddMusicView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/ClusteringAnnotationView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Annotations/MusicAnnotationView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/CarouselView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MapSearchComponentView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/Components/MusicListRowView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditDateView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/EditMapPositionView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MainTabView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapMusicInfoView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MapView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/MusicSearchView.swift
  MC3-BeyondThe3F/MC3-BeyondThe3F/View/WorkThrough/WTMusicSearchView.swift
Labels: Fix
